// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPgguh3Ga7OAoCX3FAsckTLAjZmpDUzA',
    appId: '1:479311300497:android:7daf8b25965b3c1489bc30',
    messagingSenderId: '479311300497',
    projectId: 'vproxy-1407e',
    storageBucket: 'vproxy-1407e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3g5HgcoSi20RZEfdrRmgGRNzFF5hk6o',
    appId: '1:479311300497:ios:24983b421f94721d89bc30',
    messagingSenderId: '479311300497',
    projectId: 'vproxy-1407e',
    storageBucket: 'vproxy-1407e.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi3g5HgcoSi20RZEfdrRmgGRNzFF5hk6o',
    appId: '1:479311300497:ios:24983b421f94721d89bc30',
    messagingSenderId: '479311300497',
    projectId: 'vproxy-1407e',
    storageBucket: 'vproxy-1407e.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.x',
  );

}