// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-62Dnrl4Ru7_C5kJeBt0mDwPe8tr1nY',
    appId: '1:629742529281:android:ee93ecf0934d980ef44900',
    messagingSenderId: '629742529281',
    projectId: 'vproxy-1407e-staging',
    storageBucket: 'vproxy-1407e-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWooiCE0PdPuSdU_4Wr_-Pc41nX25gTug',
    appId: '1:629742529281:ios:84e3c3c3f0752d74f44900',
    messagingSenderId: '629742529281',
    projectId: 'vproxy-1407e-staging',
    storageBucket: 'vproxy-1407e-staging.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.x.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWooiCE0PdPuSdU_4Wr_-Pc41nX25gTug',
    appId: '1:629742529281:ios:84e3c3c3f0752d74f44900',
    messagingSenderId: '629742529281',
    projectId: 'vproxy-1407e-staging',
    storageBucket: 'vproxy-1407e-staging.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.x.staging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv1ts0oZAtj3oys6NEez2tCrejja2luns',
    appId: '1:629742529281:web:9c7f6f58f012bd93f44900',
    messagingSenderId: '629742529281',
    projectId: 'vproxy-1407e-staging',
    authDomain: 'vproxy-1407e-staging.firebaseapp.com',
    storageBucket: 'vproxy-1407e-staging.firebasestorage.app',
    measurementId: 'G-VE4XPNYPS5',
  );
}
