// Copyright (C) 2026 5V Network LLC <5vnetwork@proton.me>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/tm_linux.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen_linux.yaml`.
///
class XApiLinuxBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  XApiLinuxBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  XApiLinuxBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int _GoStringLen(_GoString_ s) {
    return __GoStringLen(s);
  }

  late final __GoStringLenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(_GoString_)>>(
        '_GoStringLen',
      );
  late final __GoStringLen = __GoStringLenPtr
      .asFunction<int Function(_GoString_)>();

  ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s) {
    return __GoStringPtr(s);
  }

  late final __GoStringPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>>(
        '_GoStringPtr',
      );
  late final __GoStringPtr = __GoStringPtrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>();

  ffi.Pointer<ffi.Char> Start(ffi.Pointer<ffi.Void> p, int len) {
    return _Start(p, len);
  }

  late final _StartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Int)
        >
      >('Start');
  late final _Start =
      _StartPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, int)
      >();

  ffi.Pointer<ffi.Char> Stop() {
    return _Stop();
  }

  late final _StopPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('Stop');
  late final _Stop = _StopPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void FreeString(ffi.Pointer<ffi.Char> s) {
    return _FreeString(s);
  }

  late final _FreeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'FreeString',
      );
  late final _FreeString =
      _FreeStringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void FreeBytes(ffi.Pointer<ffi.Void> p) {
    return _FreeBytes(p);
  }

  late final _FreeBytesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'FreeBytes',
      );
  late final _FreeBytes =
      _FreeBytesPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> StartApiServer(ffi.Pointer<ffi.Void> p, int len) {
    return _StartApiServer(p, len);
  }

  late final _StartApiServerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Int)
        >
      >('StartApiServer');
  late final _StartApiServer =
      _StartApiServerPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, int)
      >();

  GenerateTls_return GenerateTls() {
    return _GenerateTls();
  }

  late final _GenerateTlsPtr =
      _lookup<ffi.NativeFunction<GenerateTls_return Function()>>('GenerateTls');
  late final _GenerateTls =
      _GenerateTlsPtr.asFunction<GenerateTls_return Function()>();
}

typedef ptrdiff_t = ffi.Long;
typedef Dartptrdiff_t = int;

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef GoInt8 = ffi.SignedChar;
typedef DartGoInt8 = int;
typedef GoUint8 = ffi.UnsignedChar;
typedef DartGoUint8 = int;
typedef GoInt16 = ffi.Short;
typedef DartGoInt16 = int;
typedef GoUint16 = ffi.UnsignedShort;
typedef DartGoUint16 = int;
typedef GoInt32 = ffi.Int;
typedef DartGoInt32 = int;
typedef GoUint32 = ffi.UnsignedInt;
typedef DartGoUint32 = int;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
typedef GoUint64 = ffi.UnsignedLongLong;
typedef DartGoUint64 = int;
typedef GoInt = GoInt64;
typedef GoUint = GoUint64;
typedef GoUintptr = ffi.Size;
typedef DartGoUintptr = int;
typedef GoFloat32 = ffi.Float;
typedef DartGoFloat32 = double;
typedef GoFloat64 = ffi.Double;
typedef DartGoFloat64 = double;
typedef GoString = _GoString_;
typedef GoMap = ffi.Pointer<ffi.Void>;
typedef GoChan = ffi.Pointer<ffi.Void>;

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

/// Return type for GenerateTls
final class GenerateTls_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.Int()
  external int r1;

  external ffi.Pointer<ffi.Char> r2;
}
