// Copyright (C) 2026 5V Network LLC <5vnetwork@proton.me>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/tm_windows.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class XApiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  XApiBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  XApiBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void do_status_change_callback(status_change_callback_t cb, int status) {
    return _do_status_change_callback(cb, status);
  }

  late final _do_status_change_callbackPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(status_change_callback_t, ffi.Int)>
      >('do_status_change_callback');
  late final _do_status_change_callback = _do_status_change_callbackPtr
      .asFunction<void Function(status_change_callback_t, int)>();

  ffi.Pointer<ffi.Char> Start(
    ffi.Pointer<ffi.Void> p,
    int len,
    self_stop_callback_t callback,
  ) {
    return _Start(p, len, callback);
  }

  late final _StartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Int,
            self_stop_callback_t,
          )
        >
      >('Start');
  late final _Start =
      _StartPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Void>,
          int,
          self_stop_callback_t,
        )
      >();

  ffi.Pointer<ffi.Char> Stop() {
    return _Stop();
  }

  late final _StopPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('Stop');
  late final _Stop = _StopPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void FreeString(ffi.Pointer<ffi.Char> s) {
    return _FreeString(s);
  }

  late final _FreeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'FreeString',
      );
  late final _FreeString =
      _FreeStringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void FreeBytes(ffi.Pointer<ffi.Void> p) {
    return _FreeBytes(p);
  }

  late final _FreeBytesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'FreeBytes',
      );
  late final _FreeBytes =
      _FreeBytesPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> StartApiServer(ffi.Pointer<ffi.Void> p, int len) {
    return _StartApiServer(p, len);
  }

  late final _StartApiServerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Int)
        >
      >('StartApiServer');
  late final _StartApiServer =
      _StartApiServerPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, int)
      >();

  GenerateTls_return GenerateTls() {
    return _GenerateTls();
  }

  late final _GenerateTlsPtr =
      _lookup<ffi.NativeFunction<GenerateTls_return Function()>>('GenerateTls');
  late final _GenerateTls =
      _GenerateTlsPtr.asFunction<GenerateTls_return Function()>();
}

typedef ptrdiff_t = ffi.LongLong;
typedef Dartptrdiff_t = int;

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef self_stop_callback_tFunction = ffi.Void Function(ffi.Pointer<ffi.Char>);
typedef Dartself_stop_callback_tFunction = void Function(ffi.Pointer<ffi.Char>);
typedef self_stop_callback_t =
    ffi.Pointer<ffi.NativeFunction<self_stop_callback_tFunction>>;
typedef status_change_callback_tFunction = ffi.Void Function(ffi.Int);
typedef Dartstatus_change_callback_tFunction = void Function(int);
typedef status_change_callback_t =
    ffi.Pointer<ffi.NativeFunction<status_change_callback_tFunction>>;
typedef GoInt8 = ffi.SignedChar;
typedef DartGoInt8 = int;
typedef GoUint8 = ffi.UnsignedChar;
typedef DartGoUint8 = int;
typedef GoInt16 = ffi.Short;
typedef DartGoInt16 = int;
typedef GoUint16 = ffi.UnsignedShort;
typedef DartGoUint16 = int;
typedef GoInt32 = ffi.Int;
typedef DartGoInt32 = int;
typedef GoUint32 = ffi.UnsignedInt;
typedef DartGoUint32 = int;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
typedef GoUint64 = ffi.UnsignedLongLong;
typedef DartGoUint64 = int;
typedef GoInt = GoInt64;
typedef GoUint = GoUint64;
typedef GoUintptr = ffi.Size;
typedef DartGoUintptr = int;
typedef GoFloat32 = ffi.Float;
typedef DartGoFloat32 = double;
typedef GoFloat64 = ffi.Double;
typedef DartGoFloat64 = double;

final class _C_float_complex extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Float> _Val;
}

typedef _Fcomplex = _C_float_complex;
typedef GoComplex64 = _Fcomplex;

final class _C_double_complex extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Double> _Val;
}

typedef _Dcomplex = _C_double_complex;
typedef GoComplex128 = _Dcomplex;
typedef GoString = _GoString_;
typedef GoMap = ffi.Pointer<ffi.Void>;
typedef GoChan = ffi.Pointer<ffi.Void>;

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

/// Return type for GenerateTls
final class GenerateTls_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.Int()
  external int r1;

  external ffi.Pointer<ffi.Char> r2;
}
