name: Build Android

on:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-vx-release]

jobs:
  build-android:
    runs-on: macos-latest
    environment: android
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Checkout dependencies
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ..
          git clone https://${GH_TOKEN}@github.com/5VNetwork/tm-plugin.git tm-plugin
          git clone https://github.com/5VNetwork/flutter_common.git flutter_common

      - name: create files
        run: |
          touch ../tm-plugin/tm_windows/assets/x.dll
          touch ../tm-plugin/tm_linux/assets/x.so
          touch ../tm-plugin/tm_linux/assets/x
          mkdir ../tm-plugin/tm_android/android/libs
          mkdir -p assets/google_fonts

      - name: Download geo
        run: |
          mkdir -p assets/geo
          curl -OL "https://github.com/5VNetwork/process-geo/releases/latest/download/simplified_geoip.dat" 
          mv simplified_geoip.dat assets/geo/simplified_geoip.dat
          curl -OL "https://github.com/5VNetwork/process-geo/releases/latest/download/simplified_geosite.dat" 
          mv simplified_geosite.dat assets/geo/simplified_geosite.dat

      - name: Download library from release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        shell: bash
        run: |
          gh release download build \
            -R 5VNetwork/vx-core \
            -p "x.aar"
          cp x.aar ../tm-plugin/tm_android/android/libs/x.aar

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Get dependencies
        run: flutter pub get

      - name: save keys
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          KEY_PROPERTY: ${{ secrets.KEY_PROPERTY }}
        run: |
          echo "$UPLOAD_KEY" | base64 --decode > android/upload-keystore.jks
          echo "$KEY_PROPERTY" | base64 --decode > android/key.properties

      - name: Set version
        id: get_version
        run: |
          BUILD_NUMBER=$(grep '^version:' pubspec.yaml | sed 's/version: .*+\(.*\)/\1/')
          VERSION_NAME=$(grep '^version:' pubspec.yaml | sed 's/version: \(.*\)+.*/\1/')
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION_NAME"
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "Extracted build number: $BUILD_NUMBER"

      - name: build bundle
        env:
          LOG_KEY: ${{ secrets.LOG_KEY }}
        run: |
          flutter build appbundle --dart-define=PLAY_STORE=true --dart-define=LOG_KEY=$LOG_KEY --flavor production --release \
            --build-name ${{ steps.get_version.outputs.version }} \
          --build-number ${{ steps.get_version.outputs.build_number }}

      - name: upload to play store
        env:
          FASTLANE_PLAY_STORE: ${{ secrets.FASTLANE_PLAY_STORE }}
        run: cd android && fastlane deploy

      - name: make releases dir
        run: mkdir -p releases

      - name: build apks
        env:
          LOG_KEY: ${{ secrets.LOG_KEY }}
        run: |
          flutter build apk  --flavor apk --dart-define=LOG_KEY=$LOG_KEY --release --split-per-abi
          mv build/app/outputs/flutter-apk/app-arm64-v8a-apk-release.apk releases/vx-arm64-v8a.apk
          zip -j releases/vx-arm64-v8a.apk.zip releases/vx-arm64-v8a.apk
          flutter build apk  --flavor apk --dart-define=LOG_KEY=$LOG_KEY --release --dart-define=LOG_KEY=$LOG_KEY
          mv build/app/outputs/flutter-apk/app-apk-release.apk releases/vx-universal.apk
          zip -j releases/vx-universal.apk.zip releases/vx-universal.apk
          rm releases/vx-universal.apk

      - name: upload apks to github release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh release upload v${{ steps.get_version.outputs.version }} \
            releases/vx-arm64-v8a.apk \
            releases/vx-arm64-v8a.apk.zip \
            releases/vx-universal.apk.zip \
            --repo ${{ github.repository_owner }}/vx \
            --clobber

